### ISSUE TITLE
Create Model For Login    

### ISSUE THREAD

**Issue by KarthikElumalai** [KarthikElumalai/ETokenSln#12]
Create Login Entity

**Comment by KarthikElumalai** [comment]
Hi Team,

As discussed in the meeting, I have created a basic model for the login.

For the testing, I ran the migration and verified that login table has created successfully.

In the same way, you also can run a migration and see that table created in your local db.

Kindly take a look and let me know your thoughts or feedback
Thanks

**Comment by nilanjansen** [comment]
Kathik please add updated by , updated date, created date, created by, IsAlive fields as part of Login Model.

**Comment by KarthikElumalai** [comment]
sure I will add the above properties as part of the login model @nilanjansen

**Comment by KarthikElumalai** [comment]
Hi Nilanjan , as discussed added the above fields to the login model.

Kindly let me know your thoughts

Thanks

**Comment by KarthikElumalai** [comment]
Hi Team,

Am closing this task, since it is completed.

Kindly let me know if you have suggestions

Thanks
Karthik
