### ISSUE TITLE
Create Azure SQL DB 

### ISSUE THREAD

**Issue by nilanjansen** [KarthikElumalai/ETokenSln#8]
Create a SQL SERVER db in azure which will consumed by the EToken App. Give access to the local IP to connect to the db.

**Comment by KarthikElumalai** [comment]
Perfect.

**Comment by nilanjansen** [comment]
1. Go to SQL Server ver. XX.
2. Enter [etoken.database.windows.net](etoken.database.windows.net) in the server name
3. Select SQL Authentication
4. Username: ETokenAdmin
5. Password: EToken@123
6. Click on Connect.

**Comment by nilanjansen** [comment]
> **### Guys Please share you IP's so that I can give you Access for this DB.**

**Comment by nilanjansen** [comment]
**Connection String**

> Server=tcp:etoken.database.windows.net,1433;Initial Catalog=ETokenMaster;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

**Comment by nilanjansen** [comment]
Checked in the connection string and updated the database. Token is getting generated. Please check everyone

**Comment by KarthikElumalai** [comment]
yeah i can also generate a token at live site.

My Token no: 

![image](https://user-images.githubusercontent.com/18113111/46944219-271e5480-d08f-11e8-888e-8babb1c49983.png)

Its really good to see that. 

Thanks @nilanjansen

**Comment by KarthikElumalai** [comment]
Hi Team,

Closing this task, since Azure Sql db has been created 

Kindly let me know if any feedbacks

Thanks
