### ISSUE TITLE
Create UI for the Login   

### ISSUE THREAD

**Issue by KarthikElumalai** [KarthikElumalai/ETokenSln#9]
1.1 - create login.cshtml page      
     1.2 - create login.js  and ajax call

**Comment by KarthikElumalai** [comment]
Hi manoj,

Can you please provide a details of where we are  standing on this task.Because  It will help us to understand what is completed and what is need to be done in the Login UI part. 


Thanks
Karthik

**Comment by nilanjansen** [comment]
Create two pages Login/Index and Login/EnterOtp
Changed .net core version to 2.2 to get the support for session in .net core
added api key in appsettings.json
